server:
  address: 127.0.0.1
  port: 8009

spring:
   datasource:
     url : jdbc:mysql://localhost:3306/boot?serverTimezone=UTC&useSSL=false&characterEncoding=utf-8
     username : root
     password : root2019
     driver-class-name : com.mysql.cj.jdbc.Driver
   redis:
     database: 0
     host: 127.0.0.1
     port: 6379
     password:
     jedis:
       pool:
         max-active: 8
         max-wait: -1
         max-idle: 8
         min-idle: 0
  #      max-active: 8
 #      max-wait: -1
 #      max-idle: 8
 #      min-idle: 0
 #    timeout: 0


mybatis:
 typeAliasesPackage: org.spring.springboot.domain
 mapperLocations: classpath:mapper/*.xml
 configuration:
    map-underscore-to-camel-case: true


mapper:
  mappers: org.spring.springboot.tkmapper.MyMapper 
  identity: MYSQL 
logging:
  level: 
    org: 
     spring: 
       springboot:
           dao: debug
    
pagehelper:
   reasonable: true
   page-size-zero: true
   params:
      pageNum: start 
      pageSize: limit
   support-methods-arguments: true
  
# params: count=countSql


